results_directory: "spec/support/results"
scripts_directory: "spec/support/scripts"

domain_under_test: "http://www.google.com"

paths_to_capture:
  home: "/"
  email: "/gmail"

scripts_to_execute:

browsers:
  - "firefox"
  - "chrome"

browser_widths: 
  - 1024

image_fuzzing: "20%"
