results_directory: "spec/support/results"
scripts_directory: "spec/support/scripts"

domain_under_test: "http://www.google.com"

paths_to_capture:
  home: "/"

scripts_to_execute:
  - "no_screenshot.rb"

browsers:
  - "firefox"
  - "chrome"

browser_widths: 
  - 320

image_fuzzing: "20%"
